/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import cloth from './clothred.glb';

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(cloth)
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    console.log('actions', actions)
    actions['KeyAction'].play()
    // actions["PlaneAction.003"].play()
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Light001" position={[4.08, 5.9, -1.01]} rotation={[1.89, 0.88, -2.05]} />
        <group name="Wind" position={[0.93, 5.63, 0.57]} rotation={[-1.97, 0.03, -0.01]} scale={4.56} />
        <group name="Harmonic" position={[-1.66, 2.42, 0.66]} rotation={[0, 1.23, 0]} scale={1.97} />
        <group name="Wind_001" position={[-3.61, 11.39, -13.49]} rotation={[-0.85, -0.41, 3.1]} scale={4.56} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.001']} morphTargetDictionary={nodes.Plane.morphTargetDictionary} morphTargetInfluences={nodes.Plane.morphTargetInfluences} position={[-1.79, 4.33, 0.05]} rotation={[1.57, 0.01, 1.42]} scale={[0.73, 1.01, 5.65]} />
      </group>
    </group>
  )
}

useGLTF.preload('/clothred.glb')
