/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef} from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'
import cloth from './clothblend.glb';

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(cloth)
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    console.log('actions', actions)
    actions['Wind.004Action'].play()
    actions["PlaneAction.003"].play()
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Light" position={[2.18, -5.29, -15.6]} rotation={[0.57, 0.88, -2.05]}>
          <pointLight name="Light_Orientation" intensity={10000} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group name="Area" position={[-0.4, -39.81, -9.25]} rotation={[0.24, 0.01, -0.34]} scale={-7.51} />
        <group name="Area001" position={[-18.5, -8.34, -9.72]} rotation={[3.13, 0.21, -1.29]} scale={-7.51} />
        <group name="Camera001" position={[-16.74, -8.62, -7.41]} rotation={[-1.24, 0.29, 1.25]}>
          <PerspectiveCamera name="Camera001_Orientation" makeDefault={false} far={100} near={0.1} fov={32.19} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group name="Wind003" position={[4.71, -25.63, 6.83]} rotation={[-0.15, 0.85, -0.47]} scale={0.33} />
        <group name="Wind001" position={[11, -15.79, -21.33]} rotation={[1.68, 0.27, -0.46]} scale={0.33} />
        <group name="Wind002" position={[6.38, -25.51, 15.15]} rotation={[-0.05, 0.53, -0.56]} scale={0.33} />
        <group name="Wind004" position={[4.56, -20.43, -13.04]} rotation={[0.61, -0.13, -0.7]} scale={0.33} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.002']} position={[9.78, -11.98, -8.99]} rotation={[0.72, -0.36, 1.59]} scale={[8.31, 1.29, -2.17]} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.003']} position={[9.78, -11.98, -8.99]} rotation={[0.72, -0.36, 1.59]} scale={[8.31, 1.29, -2.17]} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.004']} position={[9.78, -11.98, -8.99]} rotation={[0.72, -0.36, 1.59]} scale={[8.31, 1.29, -2.17]} />
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.005']} position={[9.78, -11.98, -8.99]} rotation={[0.72, -0.36, 1.59]} scale={[8.31, 1.29, -2.17]} />
      </group>
    </group>
  )
}

useGLTF.preload('/clothblend.glb')
