/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/clothblend1.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[2.18, -5.29, -15.6]} rotation={[0.57, 0.88, -2.05]}>
        <pointLight intensity={10000} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[7.13, -23.09, 0.22]} rotation={[0.57, 0.88, -2.05]} scale={0.69}>
        <pointLight intensity={10000} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-20.51, -7.68, -3.93]} rotation={[-1.27, 0.3, 1.35]}>
        <PerspectiveCamera makeDefault={false} far={100} near={0.1} fov={22.9} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.002']} position={[10.26, -11.67, -10.54]} rotation={[0.72, -0.36, 1.59]} scale={[7.86, 1.29, -2.17]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.003']} position={[6.03, -18.07, 5.92]} rotation={[-0.64, 0.07, 1.41]} scale={[7.56, 1.25, -2.09]} />
    </group>
  )
}

useGLTF.preload('/clothblend1.glb')
