/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef} from 'react'
import {useGLTF, useAnimations} from '@react-three/drei'
import cloth from './cloth_left_blend.glb';

export default function Model({...props}) {
  const group = useRef()
  const {nodes, materials, animations} = useGLTF(cloth)
  const {actions} = useAnimations(animations, group)
  useEffect(() => {
    console.log('actions', actions)
    actions['KeyAction'].play()
    // actions["PlaneAction.003"].play()
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Plane_001"
              geometry={nodes.Plane_001.geometry} material={materials['Material.001']}
              morphTargetDictionary={nodes.Plane_001.morphTargetDictionary}
              morphTargetInfluences={nodes.Plane_001.morphTargetInfluences} position={[-44.36, 41.68, 2.19]}
              rotation={[2.42, -0.41, 0.2]} scale={[-1.26, -0.44, -0.73]}/>
      </group>
    </group>
  )
}

useGLTF.preload('/cloth_left_blend.glb')
