/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef} from 'react'
import {useGLTF, PerspectiveCamera, useAnimations} from '@react-three/drei'
import cloth from './clothblend1920.glb';

export default function Model({...props}) {
  const group = useRef()
  const {nodes, materials, animations} = useGLTF(cloth)
  const {actions} = useAnimations(animations, group)
  useEffect(() => {
    console.log('actions', actions)
    actions['Area.001Action'].play()
    actions["Plane.001Action"].play()
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Light" position={[2.18, -5.29, -15.6]} rotation={[0.57, 0.88, -2.05]}>
          <pointLight name="Light_Orientation" intensity={10000} decay={2} rotation={[-Math.PI / 2, 0, 0]}/>
        </group>
        <group name="Area" position={[-0.4, -39.81, -9.25]} rotation={[0.24, 0.01, -0.34]} scale={-7.51}/>
        <group name="Area001" position={[-18.5, -8.34, -9.72]} rotation={[3.13, 0.21, -1.29]} scale={-7.51}/>
        <group name="Light001" position={[7.13, -23.09, 0.22]} rotation={[0.57, 0.88, -2.05]} scale={0.69}>
          <pointLight name="Light001_Orientation" intensity={10000} decay={2} rotation={[-Math.PI / 2, 0, 0]}/>
        </group>
        <group name="Camera001" position={[-18.51, -12.7, -4.42]} rotation={[-1.3, 0.12, 1.37]}>
          <PerspectiveCamera name="Camera001_Orientation" makeDefault={false} far={100} near={0.1} fov={22.9}
                             rotation={[-Math.PI / 2, 0, 0]}/>
        </group>
        <group name="Wind003" position={[4.71, -25.63, 6.83]} rotation={[-0.15, 0.85, -0.47]} scale={0.33}/>
        <group name="Wind001" position={[11.49, -15.48, -22.88]} rotation={[1.68, 0.27, -0.46]} scale={0.33}/>
        <group name="Wind002" position={[6.38, -25.51, 15.15]} rotation={[-0.05, 0.53, -0.56]} scale={0.33}/>
        <group name="Wind004" position={[5.04, -20.13, -14.59]} rotation={[0.61, -0.13, -0.7]} scale={0.33}/>
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.002']}
              position={[10.26, -11.67, -10.54]} rotation={[0.72, -0.36, 1.59]} scale={[8.31, 1.29, -2.17]}/>
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.002']}
              position={[3.31, -17.48, 2]} rotation={[-0.64, 0.07, 1.41]} scale={[7.56, 1.25, -2.09]}/>
      </group>
    </group>
  )
}

useGLTF.preload('/clothblend1920.glb')
