/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import cloth from './clothtest2.glb';

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(cloth)
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions['KeyAction'].play()
    // actions["PlaneAction.003"].play()
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.001']} morphTargetDictionary={nodes.Plane.morphTargetDictionary} morphTargetInfluences={nodes.Plane.morphTargetInfluences} position={[16.69, -29.56, 4.12]} rotation={[-0.23, -0.33, 2.78]} scale={[-12.75, -4.8, 3.9]} />
      </group>
    </group>
  )
}

useGLTF.preload('/clothtest2.glb')
