/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/clothblend_botl.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[2.18, -5.29, -15.6]} rotation={[0.57, 0.88, -2.05]}>
        <pointLight intensity={10000} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[7.13, -23.09, 0.22]} rotation={[0.57, 0.88, -2.05]} scale={0.69}>
        <pointLight intensity={10000} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[9.62, -14.18, -25.52]} rotation={[-1.47, -0.27, -0.21]}>
        <PerspectiveCamera makeDefault={false} far={100} near={0.1} fov={22.9} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.002']} position={[4.41, -13.17, 3.02]} rotation={[0.72, -0.36, 1.59]} scale={[4.71, 0.73, -1.23]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.001']} position={[6.66, -17.66, -1.69]} rotation={[-1.32, 0.03, 0.48]} scale={[4.71, 0.73, -1.23]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['Material.003']} position={[6.6, -17.54, 1.99]} rotation={[2.05, 0.03, 0.48]} scale={[4.71, 0.73, -1.23]} />
    </group>
  )
}

useGLTF.preload('/clothblend_botl.glb')
