/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import cloth from './test2.glb';

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(cloth)
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    console.log('actions', actions)
    actions['KeyAction'].play()
    // actions["PlaneAction.003"].play()
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Light001" position={[3.42, 0.83, 4.64]} rotation={[0.37, 0.17, -1.59]} />
        <group name="Wind" position={[0.7, 2.2, 2.86]} rotation={[3, 0.83, 0.08]} scale={4.56} />
        <group name="Harmonic" position={[-3.32, 1.29, 3.15]} rotation={[-0.42, 0.62, -1]} scale={1.97} />
        <group name="Wind_001" position={[4.66, -9.58, -6.98]} rotation={[-2.26, 0.06, 2.43]} scale={4.56} />
        <group name="Light002" position={[4.08, 5.9, -1.01]} rotation={[1.89, 0.88, -2.05]} />
        <group name="Wind001" position={[0.93, 5.63, 0.57]} rotation={[-1.97, 0.03, -0.01]} scale={4.56} />
        <group name="Harmonic001" position={[-1.66, 2.42, 0.66]} rotation={[0, 1.23, 0]} scale={1.97} />
        <group name="Wind_001001" position={[-3.61, 11.39, -13.49]} rotation={[-0.85, -0.41, 3.1]} scale={4.56} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.002']} morphTargetDictionary={nodes.Plane.morphTargetDictionary} morphTargetInfluences={nodes.Plane.morphTargetInfluences} position={[-2.91, -0.85, 4.99]} rotation={[2.99, 0.31, 0.27]} scale={[-0.11, -0.41, -0.92]} />
      </group>
    </group>
  )
}

useGLTF.preload('/test2.glb')
